#!/bin/bash

echo search for PI

grep -q BCM2708 /proc/cpuinfo
if [ $? = 0 ]; then
  echo Pi
  exit 1
fi

grep -q BCM2835 /proc/cpuinfo
if [ $? = 0 ]; then
  echo Pi
  exit 1
fi

# only for RPI deploy on docker
exit 1